# Generated by Django 2.2.6 on 2019-10-23 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость для пользователя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('content', models.TextField(verbose_name='Контент')),
                ('author', models.TextField(verbose_name='Автор')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость для пользователя')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
