# Generated by Django 2.2.6 on 2019-11-01 14:16

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=analytics.models.upload_article_images_folder, verbose_name='Фотография'),
        ),
    ]
