# Generated by Django 2.2.6 on 2019-11-01 13:56

from django.db import migrations, models
import raitings.models


class Migration(migrations.Migration):

    dependencies = [
        ('raitings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='like',
        ),
        migrations.AlterField(
            model_name='raiting',
            name='image',
            field=models.ImageField(upload_to=raitings.models.upload_raiting_images_folder, verbose_name='Фотография'),
        ),
    ]
