# Generated by Django 2.2.6 on 2019-11-01 14:16

from django.db import migrations, models
import raitings.models


class Migration(migrations.Migration):

    dependencies = [
        ('raitings', '0002_auto_20191101_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='author',
            field=models.TextField(blank=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='image',
            field=models.ImageField(blank=True, upload_to=raitings.models.upload_raiting_images_folder, verbose_name='Фотография'),
        ),
    ]
