# Generated by Django 2.2.6 on 2019-10-23 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('day', models.DateField(help_text='День события', verbose_name='День события')),
                ('start_time', models.TimeField(help_text='Начало', verbose_name='Начало')),
                ('end_time', models.TimeField(help_text='Окончание', verbose_name='Конец')),
                ('place', models.CharField(max_length=300, verbose_name='Место')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('notes', models.TextField(blank=True, help_text='Заметки', null=True, verbose_name='Заметки')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость для пользователя')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
