# Generated by Django 2.2.6 on 2019-10-23 13:26

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownloading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('url', models.CharField(help_text='URL-страницы', max_length=200, verbose_name='Ссылка')),
                ('notes', models.TextField(blank=True, help_text='Заметки', null=True, verbose_name='Заметки')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Заходим на страницу видео-Поделиться-Встроить-Копируем link, содержащий строку embeded', verbose_name='Загрузить видео')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость для пользователя')),
            ],
            options={
                'verbose_name': 'Видеообзор',
                'verbose_name_plural': 'Видеообзоры',
            },
        ),
    ]
