# Generated by Django 2.2.6 on 2019-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videooverview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownloading',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок'),
        ),
    ]
